import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          "English": "English",
          'Choose Language': 'Choose Language',
          'Sign in to your account': 'Sign in to your account',
          'Phone Number': 'Phone Number',
          'Phone': 'Phone',
          // 'Proxy': 'Proxy',
          'Pin': 'Pin',
          'LOGIN': 'LOGIN',
          "Don't have an account? ": "Don't have an account? ",
          "SIGNUP": "SIGNUP",
          "Create your account": "Create your account",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Full Name": "Full Name",
          "Select your Gender": "Select your Gender",
          "Gender": "Gender",
          "Male": "Male",
          "MALE": "Male",
          "Female": "Female",
          "FEMALE": "Female",
          "Confirm Pin": "Confirm Pin",
          "Pin (Must be atleast 6 characters)":
              "Pin (Must be atleast 6 characters)",
          "Select an organization": "Select an organization",
          // "Confirm OTP": "Confirm OTP",
          "I understood the terms and policies.":
              "I understood the terms and policies.",
          "Have an account?": "Have an account?",
          "If you didn't get the message tap the resend button bellow.":
              "If you didn't get the message tap the resend button bellow.",
          "Loanable Fund": "Loanable Fund",
          "Bronze": "Bronze",
          "Silver": "Silver",
          "Gold": "Gold",
          "Premium": "Premium",
          "Members": "Members",
          "Member": "Member",
          "Transactions": "Transactions",
          "Loans": "Loans",
          "Awareness": "Awareness",
          "Start": "Start",
          "Start Meeting": "Start Meeting",
          "Yes": "Yes",
          "Okay": "Okay",
          "No": "No",
          "Yes / No": "Yes / No",
          "Cancel": "Cancel",
          "Save": "Save",
          "The meeting date is not due.": "The meeting date is not due.",
          "Do you want to start/continue the meeting?":
              "Do you want to start/continue the meeting?",
          "Meetings": "Meetings",
          "Tip of the day": "Tip of the day",
          "stay informed": "stay informed",
          "Recent Updates": "Recent Updates",
          "Total saving": "Total saving",
          "Total Social Fund": "Total Social Fund",
          "Total Loan Disbursed": "Total Loan Disbursed",
          "Total Loan Repayed": "Total Loan Repayed",
          "Total Social Fund released": "Total Social Fund released",
          "Total members": "Total members",
          "Proxy": "Proxy",
          "Add Member": "Add Member",
          "Add": "Add",
          "GROUP_ADMIN": "GROUP_ADMIN",
          "Manager": "Manager",
          "VSLA Role": "VSLA Role",
          "Saving": "Saving",
          "Loan Despersal": "Loan Despersal",
          "Loan Repayment": "Loan Repayment",
          "Social Funds": "Social Funds",
          "All Transactions": "All Transactions",
          "Recieved": "Recieved",
          "Issued": "Issued",
          "Repaid": "Repaid",
          "Pending": "Pending ",
          "Active": "Active",
          "Repaid ": "Repaid ",
          "Rejected": "Rejected ",
          "issued": "issued",
          "Meeting Agenda": "Meeting Agenda",
          "Close Meeting": "Close Meeting",
          "Pay penalty here": "Pay penalty here",
          "Reason": "Reason",
          "Meeting closed successfully": "Meeting closed successfully",
          "No Penalties found": "No Penalties found",
          "Loan Priority List": "Loan Priority List",
          // "Repaid": "ተከፍሏል",
          "pending": "pending",
          "active": "active",
          "repaid": "repaid",
          "rejected": "rejected",
          "All": "All",
          "Apply for Loan": "Apply for Loan",
          "Filter by": "Filter by",
          "View Loan Details": "View Loan Details",
          "Requester": "Requester",
          "Amount": "Amount",
          "Interest Rate": "Interest Rate",
          "Status": "Status",
          "Loan Amount": "Loan Amount",
          "Loan Description": "Loan Description",
          "Desc. ": "Desc. ",
          "Description": "Description",
          "Repayment plan": "Repayment plan",
          "1 Week": "1 Week",
          "2 Weeks": "2 Weeks",
          "1 Month": "1 Month",
          "45 Days": "45 Days",
          "2 Months": "2 Months",
          "3 Months": "3 Months",
          "Repay Loan": "Repay Loan",
          "As of": "As of",
          "Due Date": "Due Date",
          "Repayment Amount": "Repayment Amount",
          "Confirm Reject": "Confirm Reject",
          "Are you sure you want to reject ":
              "Are you sure you want to reject ",
          "'s loan?": "'s loan?",
          "Loan rejected Successfuly": "Loan rejected Successfuly",
          "Loan approved Successfuly": "Loan approved Successfuly",
          "Amount repaid Successfuly": "Amount repaid Successfuly",
          "Are you sure you want to approve ":
              "Are you sure you want to approve",
          "Loan rejection failed; please try again":
              "Loan rejection failed; please try again",
          "Reject": "Reject",
          "Confirm Payment": "Confirm Payment",
          "Are you sure you want to repay ": "Are you sure you want to repay ",
          "'s loan?3": "'s loan?",
          "Loan approval failed; please try again":
              "Loan approval failed; please try again",
          "Your maximum loan amount is": "Your maximum loan amount is",
          "Health, Tips & Tricks...": "Health, Tips & Tricks...",
          "Be aware of...": "Be aware of...",
          "All Videos": "All Videos",
          "Coffee shop tips...": "Coffee shop tips...",
          "Inactive": "Inactive",
          "Attendance": "Attendance",
          "Either Attendance has not been filled or payment is already done for ":
              "Either Attendance has not been filled or payment is already done for ",
          "Current Round": "Current Round",
          "Paid": "Paid",
          "Unpaid": "Unpaid",
          "Add Round Payment": "Add Round Payment",
          "Add Social Fund": "Add Social Fund",
          "Add Penalty Payment": "Add Penalty Payment",
          "Add Expenditure Payment": "Add Expenditure Payment",
          "Are you sure you want to add ": "Are you sure you want to add ",
          " Birr to ": " Birr to ",
          " Birr to Expenditure": " Birr to Expenditure",
          "Please enter an amount": "Please enter an amount",
          // "Saving": "Saving",
          "Social funds": "Social funds",
          "Penalty payments": "Penalty payments",
          "Penalties": "Penalties",
          "Round Payment": "Round Payment",
          "Pay-Social Fund": "Pay-Social Fund",
          "Caution": "Caution",
          "Round": "Round",
          "Next Meeting Day": "Next Meeting Day",
          "Days": "Days",
          "Report": "Report",
          "Expenditure": "Expenditure",
          "Pay-Expenditure": "Pay-Expenditure",
          // "Loan Priority List": "Loan Priority List",
          "Net Share": "Net Share",
          "Gross Share": "Gross Share",
          "Contr.": "Contr.",
          "Debt": "Debt",
          "Link with Banks": "Link with Banks",
          "Cooperative Bank of Oromia": "Cooperative Bank of Oromia",
          "Link": "Link",
          "Other Bank": "Other Bank",
          "Ready to link with the bank of your choice?":
              "Ready to link with the bank of your choice?",
          "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities":
              "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities",
          "Get Started": "Get Started",
          "Terms of service": "Terms of service",
          "Privacy policy": "Privacy policy",
          "Language": "Language",
          "Help and support": "Help and support",
          "Logout": "Logout",
          "Invalid phone number format": "Invalid phone number format",
          "Invalid password": "Invalid password",
          "Invalid username or password": "Invalid username or password",
          "Something went wrong, please Check your network connection":
              "Something went wrong, please Check your network connection",
          "press again to exit": "press again to exit",
          "First name is mandatory": "First name is mandatory",
          "Last name is mandatory": "Last name is mandatory",
          "Please agree with our policy and terms":
              "Please agree with our policy and terms",
          "Gender is a mandatory field": "Gender is a mandatory field",
          "Something went wrong, please try again":
              "Something went wrong, please try again",
          "Account Created Successfuly": "Account Created Successfuly",
          "This phone number is already registered":
              "This phone number is already registered",
          "Account creation failed please try again":
              "Account creation failed please try again",
          "Otp verified successfully": "Otp verified successfully",
          "This field is required": "This field is required",
          "Please enter only letters": "Please enter only letters",
          "Payment added Successfuly": "Payment added Successfuly",
          "payment process failed; please try again":
              "payment process failed; please try again",
          "Do you want to Logout": "Do you want to Logout",
          "Confirm Exit": "Confirm Exit",
          "Confirm Deletion": "Confirm Deletion",
          "Are you sure you want to delete this user":
              "Are you sure you want to delete this user",
          "Account Deleted Successfuly": "Account Deleted Successfuly",
          "Account Updated Successfuly": "Account Updated Successfuly",
          "Meeting created successfully": "Meeting created successfully",
          // "Amount repaid Successfuly": "Amount repaid Successfuly",
          "Loan repayment failed; please try again":
              "Loan repayment failed; please try again",
          "please select a member": "please select a member",
          "please enter a loan amount": "please enter a loan amount",
          "The max amount of loan is": "The max amount of loan is",
          "Please enter a description": "Please enter a description",
          "please select a plan": "please select a plan",
          "Loan applied successfully": "Loan applied successfully",
          "Password must be at least 6 characters long":
              "Password must be at least 6 characters long",
          "Password unmatched": "Password unmatched",
          "Phone number is required": "Phone number is required",
          "Enter a valid phone number": "Enter a valid phone number",
          "Member added successfully": "Member added successfully",
          "Meeting type is required": "Meeting type is required",
          "Meeting inteval is required": "Meeting inteval is required",
          "Meeting activated successfully": "Meeting activated successfully",
          "Meeting edited successfully": "Meeting edited successfully",
          "Meeting deleted successfully": "Meeting deleted successfully",
          "Are you sure, This process is irreversible":
              "Are you sure, This process is irreversible",
          "Attendance saved successfully": "Attendance saved successfully",
          "Please fill attendace first": "Please fill attendace first",
          // "No Penalties found": "No Penalties found",
          "Are you sure you want to add ..... Birr to ....":
              "Are you sure you want to add ..... Birr to ....",
          // "Meeting closed successfully": "Meeting closed successfully",
          "Please fill attendance before any payment":
              "Please fill attendance before any payment",
        },
        //AMHARIC LANGUAGE
        'am_ET': {
          'English': 'አማርኛ',
          'Choose Language': 'ቋንቋ ይምረጡ',
          'Sign in to your account': 'ወደ አካውንትዎ ይግቡ',
          'Phone Number': 'ስልክ ቁጥር',
          'Phone': 'ስልክ',
          'Pin': 'ምሥጢራዊ ቁጥር',
          'LOGIN': 'ግባ',
          "Don't have an account?": "አካውንት የለዎትም?",
          "SIGNUP": "ይመዝገቡ",
          "Create your account": "አካውንትዎን ይፍጠሩ",
          "First Name": "ስም",
          "Last Name": "የአባት ስም",
          "Full Name": "ሙሉ ስም",
          "Select your Gender": "ጾታዎን ይምረጡ",
          "Gender": "ጾታ",
          "Male": "ወንድ",
          "MALE": "ወንድ",
          "Female": "ሴት",
          "FEMALE": "ሴት",
          "Confirm Pin": "ምሥጢራዊ ቁጥሩን ያረጋግጡ",
          "Pin (Must be atleast 6 characters)":
              "ምሥጢራዊ ቁጥር (ቢያንስ 6 ካራክተር መሆን አለበት)",
          "Select an organization": "ድርጅት ይምረጡ",
          // "Confirm OTP": "Confirm OTP",
          "I understood the terms and policies.": "ሕግና ደንቦቹን ተረድቻለሁ።",
          "Have an account?": "አካውንት አለዎት?",
          // "If you didn't get the message tap the resend button bellow.":
          //     "If you didn't get the message tap the resend button bellow.",
          "Loanable Fund": "የብድር ፈንድ",
          "Bronze": "ነሐስ",
          "Silver": "ብር",
          "Gold": "ወርቅ",
          "Premium": "ፕሪሚየም",
          "Members": "አባላት",
          "Member": "አባል",
          "Transactions": "ግብይቶች",
          "Loans": "ብድሮች",
          "Awareness": "ግንዛቤ",
          "Start": "ይጀምሩ",
          "Start Meeting": "ስብሰባ ጀምር",
          "Do you want to start/continue the meeting?":
              "ስብሰባውን መጀመር/መቀጠል ይፈልጋሉ?",
          "Meetings": "ስብሰባዎች",
          "Yes": "አዎ",
          "Okay": "እሺ",
          "No": "አይ",
          "Yes / No": "አዎ / አይ",
          "Cancel": "ተመለስ",
          "Save": "መዝግብ",
          "The meeting date is not due.": "የመሰብሰቢያው ቀን አልደረሰም።",
          "Tip of the day": "የዕለቱ ምክር",
          "stay informed": "አዳዲስ መረጃዎችን ያግኙ",
          "Recent Updates": "የቅርብ ጊዜ መረጃዎች",
          "Total saving": "ጠቅላላ ቁጠባ",
          "Total Social Fund": "ጠቅላላ ማኅበራዊ ፈንድ",
          "Total Loan Disbursed": "ጠቅላላ የተከፈለ ብድር",
          "Total Loan Repayed": "ጠቅላላ የተመለሰ ብድር",
          "Total Social Fund released": "ጠቅላላ የተለቀቀ ማኅበራዊ ፈንድ",
          "Total members": "ጠቅላላ የአባላት ቁጥር",
          "Proxy": "ወኪል",
          "Add Member": "አባል ጨምር",
          "Add": "ክፈል",
          "GROUP_ADMIN": "ቡድን መሪ",
          "Manager": "አስተዳዳሪ",
          "VSLA Role": "VSLA ሚና",
          "Saving": "ቁጠባ",
          "Loan Despersal": "ብድር መልቀቅ",
          "Loan Repayment": "ብድር መመለስ",
          "Social Funds": "ማኅበራዊ ፈንዶች",
          "All Transactions": "ሁሉም ግብይቶች",
          "Recieved": "ተቀብለዋል",
          "Issued": "ተሰጥቷል",
          // "Repaid": "ተከፍሏል",
          "Pending": "በሂደት ላይ",
          "Active": "በስራ ላይ",
          "Repaid": "የተከፈለ",
          "Rejected": "ውድቅ የተደረገ",
          "issued": "ተሰጥቷል",
          "Meeting Agenda": "የመወያያ ርእስ",
          "Close Meeting": "ስብሰባውን አጠናቅ",
          "Pay penalty here": "ቅጣቱን እዚህ ይክፈሉ",
          "Reason": "የቅጣቱ ምክንያት",
          "Meeting closed successfully": "ስብሰባው በተሳካ ሁኔታ ተዘግቷል",
          // "Repaid": "ተከፍሏል",
          "pending": "በሂደት ላይ",
          "active": "በስራ ላይ",
          "repaid": "የተከፈለ",
          "rejected": "ውድቅ የተደረገ",
          "All": "ሁሉም",
          "Apply for Loan": "ብድር ለማግኘት ያመልክቱ",
          "Filter by": "ማጣሪያ በ...",
          "Requester": "ጠያቂ",
          "Amount": "መጠን",
          "Interest Rate": "የወለድ መጠን",
          "Status": "የብድር ሁኔታ",
          "Loan Amount": "የብድር መጠን",
          "Loan Description": "የብድር ዝርዝር መግለጫ",
          "Desc. ": "መግለጫ ",
          "Description": "መግለጫ",
          "Repayment plan": "የብድር አከፋፈል ሁኔታ",
          "1 Week": "1 ሳምንት",
          "2 Weeks": "2 ሳምንት",
          "1 Month": "1 ወር",
          "45 Days": "45 ቀን",
          "2 Months": "2 ወር",
          "3 Months": "3 ወር",
          "Repay Loan": "ብድር ክፈል",
          "As of": "ቀን",
          "Due Date": "የመጨረሻ ማስረከቢያ ቀን",
          "Repayment Amount": "የመክፈያ መጠን",
          "Confirm Reject": "ክልከላውን ያረጋግጡ",
          "View Loan Details": "የብድር ዝርዝሮችን ይመልከቱ",
          "Are you sure you want to reject ": "እርግጠኛ ነዎት የ",
          "'s loan?": "ን ብድር ውድቅ ማድረግ ይፈልጋሉ?",
          "Are you sure you want to approve ": "እርግጠኛ ነዎት የ",
          "'s loan?2": "ን ብድር መፍቀድ ይፈልጋሉ?",
          "Are you sure you want to repay ": "እርግጠኛ ነዎት የ",
          "'s loan?3": "ን ብድር መክፈል ይፈልጋሉ?",
          "Loan rejected Successfuly": "ብድሩ በተሳካ ሁኔታ ውድቅ ተደርጓል",
          "Loan approved Successfuly": "ብድር በተሳካ ሁኔታ ጸድቋል",
          "Amount repaid Successfuly": "ብድሩ በተሳካ ሁኔታ ተከፍሏል",
          "Loan rejection failed; please try again":
              "ብድሩን ውድቅ ማድረግ አልተሳካም; እባክዎ ዳግም ይሞክሩ",
          "Reject": "ውድቅ አድርግ",
          "Confirm Payment": "ክፍያ ያረጋግጡ",
          "Loan approval failed; please try again":
              "የብድር ፍቃድ አልተሳካም; እባክዎ ዳግም ይሞክሩ",
          "Your maximum loan amount is": "ከፍተኛ የብድር መጠንዎ ",
          "Health, Tips & Tricks...": "ጤና፣ ምክሮችና ብልሃቶች…",
          "Be aware of...": "ከ…ጥንቃቄ ያድርጉ",
          "All Videos": "ሁሉም ቪዲዮዎች",
          "Coffee shop tips...": "የሻይ ቡና ቤት ምክሮች ",
          "Attendance": "የተገኘ",
          "Either Attendance has not been filled or payment is already done for ":
              "ወይ አቴንዳንስ አልተሞላም አልያም ክፍያ ተፈጽሟል ለ",
          "Current Round": "የአሁን ዙር",
          "Paid": "ተከፍሏል",
          "Unpaid": "አልተከፈለም",
          "Add Round Payment": "የዙር ክፍያ ይፈጽሙ",
          "Add Social Fund": "የማህበራዊ መዋጮ ክፍያ ይፈጽሙ",
          "Add Penalty Payment": "የቅጣት ክፍያ ይፈጽሙ",
          "Add Expenditure Payment": "የወጪ ክፍያን ይመዝግቡ",
          "Are you sure you want to add ": "እርግጠኛ ነዎት ",
          " Birr to ": " ብር ለመክፈል ለ ",
          " Birr to Expenditure": " ብር ለመክፈል",
          "Please enter an amount": "እባክዎ የብሩን ምጠን ያስገቡ",
          "Loan Priority List": "አጠቃላይ የብድር ቅደም ተከተል",
          // "Saving": "Saving",
          "Social funds": "ማህበራዊ ፈንድ",
          "Penalty payments": "የቅጣት ክፍያዎች",
          "Penalties": "ቅጣቶች",
          "Inactive": "የማይሰራ",
          "Round Payment": "የዙር ክፍያ",
          "Pay-Social Fund": "ማህበራዊ ፈንድ ክፈል",
          "Caution": "ይጠንቀቁ",
          "Round": "ዙር",
          "Next Meeting Day": "ቀጣይ የስብሰባ ቀን",
          "Days": "ቀናት",
          "Report": "ሪፖርት",
          "Expenditure": "ወጪ",
          "Pay-Expenditure": "ወጪ መዝግብ",
          // "Loan Priority List": "ቅድሚያ የሚሰጠው የብድር ዝርዝር",
          "Net Share": "የተጣራ ድርሻ",
          "Gross Share": "ጠቅላላ ድርሻ",
          "Contr.": "አስተዋጽዖ",
          "Debt": "እዳ",
          "Link with Banks": "ከባንኮች ጋር ትስስር ፍጠር",
          "Cooperative Bank of Oromia": "የኦሮሚያ ህብረት ስራ ባንክ",
          "Link": "ትስስር",
          "Other Bank": "ሌላ ባንክ",
          "Ready to link with the bank of your choice?":
              "ከሚፈልጉት ባንክ ጋር ለመተሳሰር ዝግጁ ነዎት?",
          "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities":
              "ባንኮች እርስዎ የሚያደርጓቸውን የፋይናንስ ግብይቶች መዝግበው የሚይዙ ሲሆን ይህም በተለይ ብድር፣ የገንዘብ ድጋፍ ወይም ሌሎች የፋይናንስ እድሎችን ለማግኘት በሚያመለክቱበት ወቅት ጠቃሚ ነው።",
          "Get Started": "እንጀምር",
          "Terms of service": "ደንብና ሁኔታዎች",
          "Privacy policy": "የግል መረጃ ጥበቃ ፖሊሲ",
          "Language": "ቋንቋ",
          "Help and support": "እርዳታና ድጋፍ",
          "Logout": "ይውጡ",
          "Invalid phone number format": "የተሳሳተ የስልክ ቁጥር አጻጻፍ ተጠቅመዋል",
          "Invalid password": "የተሳሳተ የይለፍ ቃል",
          "Invalid username or password": "የተሳሳተ ዩዘርኔም ወይም የይለፍ ቃል አስገብተዋል",
          "Something went wrong, please Check your network connection":
              "የሆነ ችግር ተፈጥሯል። እባክዎ የኢንተርኔት ግንኙነት መኖሩን ያረጋግጡ። ",
          "press again to exit": "ለመውጣት ደግመው ይጫኑ",
          "First name is mandatory": "ስምዎን ማስገባት አለብዎት",
          "Last name is mandatory": "የአባትዎን ስም ማስገባት አለብዎት",
          "Please agree with our policy and terms":
              "የተሳሳተ የስልክ ቁጥር አጻጻፍ ተጠቅመዋል",
          "Gender is a mandatory field": "ጾታ ማስገባት አለብዎት",
          "Something went wrong, please try again":
              "የሆነ ችግር ተፈጥሯል። እባክዎ እንደገና ይሞክሩ",
          "Account Created Successfuly": "አካውንትዎ በተሳካ ሁኔታ ተፈጥሯል",
          "This phone number is already registered":
              "ይህ የስልክ ቁጥር ቀድሞውኑ የተመዘገበ ነው",
          "Account creation failed please try again":
              "አካውንት መፍጠር አልተቻለም። እባክዎ እንደገና ይሞክሩ",
          "Otp verified successfully": "ጊዜያዊ የይለፍ ቃሉን አረጋግጠናል",
          "This field is required": "ይሄ ቦታ መሞላት አለበት",
          "Please enter only letters": "እባክዎ ፊደል ብቻ ያስገቡ",
          "Payment added Successfuly": "ክፍያው ክፍያው በተሳካ ሁኔታ ተፈጽሟል",
          "payment process failed; please try again":
              "ክፍያውን ማጠናቀቅ አልተቻለም። እባክዎ እንደገና ይሞክሩ",
          "Do you want to Logout": "ዘግተው መውጣት ይፈልጋሉ?",
          "Confirm Exit": "መውጣት እንደሚፈልጉ ያረጋግጡ",
          "Confirm Deletion": "መሰረዝ እንደሚፈልጉ ያረጋግጡ",
          "Are you sure you want to delete this user?":
              "እርግጠኛ ነዎት ይህን ተጠቃሚ መሰረዝ ይፈልጋሉ?",
          "Account Deleted Successfuly": "አካውንቱ ተሰርዟል",
          "Account Updated Successfuly": "አካውንቱ ተሻሽሏል",
          "Meeting created successfully": "የስብሰባ ጊዜ ሠሌዳ ተፈጥሯል",
          // "Amount repaid Successfuly": "ገንዘቡ ተከፍሏል",
          "Loan repayment failed; please try again":
              "ብድሩን መክፈል አልተቻለም። እባክዎ እንደገና ይሞክሩ",
          "please select a member": "እባክዎ አባል ይምረጡ",
          "please enter a loan amount": "እባክዎ የብድሩን መጠን ያስገቡ",
          "The max amount of loan is": "ከፍተኛው የብድር መጠን ------- ነው",
          "Please enter a description": "እባክዎ መግለጫ ያስገቡ",
          "please select a plan": "እባክዎ እቅድ ይምረጡ",
          "Loan applied successfully": "ብድሩ በትክክል ተልል",
          "Password must be at least 6 characters long":
              "የይለፍ ቃል ቢያንስ 6 ፊደል መሆን አለበት",
          "Password unmatched": "ያስገቡት የይለፍ ቃል የተለያየ ነው",
          "Phone number is required": "ስልክ ቁጥር መሞላት አለበት",
          "Enter a valid phone number": "ትክክለኛ ስልክ ቁጥር ያስገቡ",
          "Member added successfully": "አባል በትክክል ተጨምሯል",
          "Meeting type is required": "የስብሰባው ዓይነት መሞላት አለበት",
          "Meeting inteval is required": "የስብሰባው መጀመሪያና ማብቂያ መሞላት አለበት",
          "Meeting activated successfully": "የስብሰባ ጊዜ ሠሌዳ እንዲሠራ ተደርጓል",
          "Meeting edited successfully": "የስብሰባ ጊዜ ሠሌዳ ተስተካክሏል",
          "Meeting deleted successfully": "የስብሰባ ጊዜ ሠሌዳ ተሰርዟል",
          "Are you sure, This process is irreversible":
              "እርግጠኛ ነዎት? ይህን ሂደት ማቋረጥ አይቻልም",
          "Attendance saved successfully": "አቴንዳንስ እንዲቀመጥ ተደርጓል",
          "Please fill attendace first": "እባክዎ መጀመሪያ አቴንዳንስ ይሙሉ",
          "No Penalties found": "ቅጣት የተጣለበት ሰው የለም",
          "Are you sure you want to add ..... Birr to ....":
              "እርግጠኛ ነዎት ..... ብር ወደ .... መጨመር ይፈልጋሉ?",
          // "Meeting closed successfully": "ስብሰባ በትክክል ተዘግቷል",
          "Please fill attendance before any payment":
              "እባክዎ ምንም ዓይነት ክፍያ ከመፈጸምዎ በፊት አቴንዳንስ ይሙሉ",
        },
        //KANNADA LANGUAGE
        'or_ET': {
          "English": "Afaan Oromoo",
          'Choose Language': 'Afaan Filadhu',
          'Sign in to your account': 'Akkaawuntii keessan seena',
          'Phone Number': 'Lakkoofsa Bilbilaa',
          'Phone': 'Bilbila',
          'Proxy': "Bakka bu'aa",
          'Pin': "Lakkoofsa Iciitii",
          'LOGIN': 'SEENAA',
          "Don't have an account? ": "Akkaawuntii hin qabduu?",
          "SIGNUP": "Seenii",
          "Create your account": "Akkaawuntii keessan banaa",
          "First Name": "Maqaa",
          "Last Name": "Maqaa Abbaa",
          "Full Name": "Maqaa Guutuu",
          "Select your Gender": "Saala kee filadhu",
          "Gender": "Saala",
          "Male": "Dhiira",
          "MALE": "Dhiira",
          "Female": "Dhalaa",
          "FEMALE": "Dhalaa",
          "Confirm Pin": "Piinii mirkaneessi",
          "Pin (Must be atleast 6 characters)":
              "Pin (Yoo xiqqaate arfiilee 6 ta'uu qaba)",
          "Select an organization": "Dhaabbata filadhu",
          "Confirm OTP": "OTP Mirkaneessi",
          "I understood the terms and policies.":
              "Jechootaa fi imaammata hubadheera.",
          "Have an account?": "Akkaawuntii qabdaa?",
          "If you didn't get the message tap the resend button bellow.":
              "Yoo ergaa sana hin arganne ta'e bakka resend jedhu armaan gadii tuqi.",
          "Loanable Fund": "Fandii Liqii",
          "Bronze": "Naasaa",
          "Silver": "Meetii",
          "Gold": "Warqee",
          "Premium": "Premium",
          "Members": "Miseensota",
          "Member": "Miseensa",
          "Transactions": "Daddabarsa",
          "Loans": "Liqii",
          "Awareness": "Hubannoo",
          "Start": "Jalqaba",
          "Start Meeting": "Walgahii Jalqabaa",
          "Yes": "Eeyyee",
          "Okay": "Tole",
          "No": "Lakki",
          "Yes / No": "Eeyyee / Lakki",
          "Cancel": "Haqi",
          "Save": "Galmeessi",
          "The meeting date is not due.": "Guyyaan walgahii hin geenye.",
          "Do you want to start/continue the meeting?":
              "Walgahii jalqabuu/itti fufuu barbaadduu?",
          "Meetings": "Walgahii",
          "Tip of the day": "Gorsa guyyaa",
          "stay informed": "odeeffannoo qabaadhaa",
          "Recent Updates": "Foyya'iinsa Dhiheenyaa",
          "Total saving": "Qusannaa waliigalaa",
          "Total Social Fund": "Fandii Hawaasummaa Waliigalaa",
          "Total Loan Disbursed": "Liqii Waliigalaa Kenname",
          "Total Loan Repayed": "Liqii Waliigalaa Deebi'e",
          "Total Social Fund released":
              "Fandii Hawaasummaa Waliigalaa gadhiifame",
          "Total members": "Miseensoota waliigalaa",
          "Proxy": "Bakka bu'aa",
          "Add Member": "Miseensa Dabaluu",
          "Add": "Dabala",
          "GROUP_ADMIN": "Bulchaa Garee",
          "Manager": "Hoogganaa",
          "VSLA Role": "Gahee VSLA",
          "Saving": "Qusachuu",
          "Loan Despersal": "Liqii Dhiisuu",
          "Loan Repayment": "Kaffaltii Liqii",
          "Social Funds": "Maallaqa Hawaasummaa",
          "All Transactions": "Daddabarsa Hundaa",
          "Recieved": "Fudhatame",
          "Issued": "Ragaa'ee",
          "Repaid": "Kafalameeraa",
          "Pending": "Hin Xumuramin ",
          "Active": "Socho'aa",
          "Repaid ": "Kafalameeraa ",
          "Rejected": "kufeeraa ",
          "issued": "ragaa'ee",
          "Meeting Agenda": "Ajandaa Walgahii",
          "Close Meeting": "Walgahii cufameera",
          "Pay penalty here": "Asitti adabbii kaffalaa",
          "Reason": "Sababa",
          "Meeting closed successfully": "Walgahiin milkaa'inaan cufame",
          "No Penalties found": "Adabbiin hin argamne",
          "Loan Priority List": "Tarree Dursa Liqii",
          // "Repaid": "ተከፍሏል",
          "pending": "Hin Xumuramin",
          "active": "Socho'aa",
          "repaid": "Kafalameeraa",
          "rejected": "Kuufeeraa",
          "All": "Hundaa",
          "Apply for Loan": "Liqii Iyyachuu",
          "Filter by": "Calallii",
          "View Loan Details": "Ibsa Liqii Ilaali",
          "Requester": "Gaafataa",
          "Amount": "Hanga",
          "Interest Rate": "Dhala",
          "Status": "Haala",
          "Loan Amount": "Hanga Liqii",
          "Loan Description": "Ibsa Liqii",
          "Desc. ": "Ibsa",
          "Description": "Ibsa",
          "Repayment plan": "Karoora kaffaltii deebisuu",
          "1 Week": "Torban 1",
          "2 Weeks": "Torban 2",
          "1 Month": "Ji'a 1",
          "45 Days": "Guyyaa 45",
          "2 Months": "Ji'a 2",
          "3 Months": "Ji'a 3",
          "Repay Loan": "Liqii Deebisuu",
          "As of": "Akka",
          "Due Date": "Guyyaa Dheebuu",
          "Repayment Amount": "Hanga Kaffaltii Deebi'uu",
          "Confirm Reject": "Diduu Mirkaneessi",
          "Are you sure you want to reject ":
              "Diduu akka barbaaddu mirkaneeffatteettaa ",
          "'s loan?": "'s liqii?",
          "Loan rejected Successfuly": "Liqiin Milkaa'inaan dide",
          "Loan approved Successfuly": "Liqiin Milkaa'inaan raggaasifame",
          "Amount repaid Successfuly": "Maallaqa Milkaa'inaan deebi'e",
          "Are you sure you want to approve ":
              "Raggaasisuu akka barbaaddu mirkaneeffatteettaa",
          "Loan rejection failed; please try again":
              "Liqii diduu hin milkoofne; maaloo irra deebi'ii yaalaa",
          "Reject": "Kufeeraa",
          "Confirm Payment": "Kaffaltii Mirkaneessi",
          "Are you sure you want to repay ":
              "Deebisuu akka barbaaddu mirkaneeffatteettaa ",
          "'s loan?3": "'s liqii?3?",
          "Loan approval failed; please try again":
              "Eeyyama liqii hin milkoofne; maaloo irra deebi'ii yaali",
          "Your maximum loan amount is": "Hanga liqii kee guddaan",
          "Health, Tips & Tricks...": "Gorsa Fayyaa...",
          "Be aware of...": "Of... irratti hubadhu...",
          "All Videos": "Viidiyoo hunda",
          "Coffee shop tips...": "Gorsa mana bunaa...",
          "Inactive": "Sochii hin qabne",
          "Attendance": "Argama",
          "Either Attendance has not been filled or payment is already done for ":
              "Yookiin attendenciin hin guutamne yookaan kaffaltiin duraan raawwatameera ",
          "Current Round": "Marsaa Ammaa",
          "Paid": "Kaffaltii",
          "Unpaid": "kan hin kaffalamnee",
          "Add Round Payment": "Marsaa Kaffaltii  Dabaluu",
          "Add Social Fund": "Fandii Hawaasummaa Dabaluu",
          "Add Penalty Payment": "Kaffaltii Adabbii Dabaluu",
          "Add Expenditure Payment": "Kaffaltii Baasii Dabaluu",
          // "Are you sure you want to add ":
          //     "Dabaluu akka barbaaddu mirkaneeffatteettaa ",
          // " Birr to ": " Birrii gara ",
          "Are you sure you want to add ": "Birrii ",
          " Birr to ": " dabaluu akka barbaaddu mirkaneeffatteertaa gara ",
          " Birr to Expenditure": " Birrii Baasii",
          "Please enter an amount": "Maaloo hanga galchi",
          // "Saving": "Saving",
          "Social funds": "Maallaqa hawaasummaa",
          "Penalty payments": "Kaffaltii adabbii",
          "Penalties": "Adabbii",
          "Round Payment": "Marsaa Kaffaltii",
          "Pay-Social Fund": "Fandii Hawaasummaa Kaffaltii",
          "Caution": "Of eeggannoo",
          "Round": "Marsaa",
          "Next Meeting Day": "Guyyaa Walgahii Itti Aanu",
          "Days": "Guyyoota",
          "Report": "Gabaasa",
          "Expenditure": "Baasii",
          "Pay-Expenditure": "Kaffaltii-Baasii",
          // "Loan Priority List": "Loan Priority List",
          "Net Share": "Qoodni Qulqulluu",
          "Gross Share": "Gahee Waliigalaa",
          "Contr.": "Gumaacha",
          "Debt": "Liqaa",
          "Link with Banks": "Baankota waliin walitti hidhamiinsa",
          "Cooperative Bank of Oromia": "Baankii Hojii Gamtaa Oromiyaa",
          "Link": "Linkii",
          "Other Bank": "Baankii Biroo",
          "Ready to link with the bank of your choice?":
              "Baankii filannoo keessanii waliin walqabsiisuuf qophiidhaa?",
          "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities":
              "Baankonni galmee daldala faayinaansii keessanii ni qabatu, kunis keessumaa yeroo liqii, gargaarsa, ykn carraa maallaqaa biroo iyyattan faayidaa qabaachuu danda'a",
          "Get Started": "Jalqabi",
          "Terms of service": "Haala tajaajilaa",
          "Privacy policy": "Imaammata dhuunfaa",
          "Language": "Afaan",
          "Help and support": "Gargaarsa fi deeggarsa",
          "Logout": "Ba'ii",
          "Invalid phone number format":
              "Akkaataa lakkoofsa bilbilaa sirrii hin taane",
          "Invalid password": "Jecha icciitii sirrii hin taane",
          "Invalid username or password":
              "Maqaa fayyadamaa ykn jecha icciitii sirrii hin taane",
          "Something went wrong, please Check your network connection":
              "Wanti tokko dogoggora ta'e, maaloo Network connection keessan Check godhaa",
          "press again to exit": "ba'uuf ammas dhiibi",
          "First name is mandatory": "Maqaan dirqama",
          "Last name is mandatory": "Maqaan Abbaa dirqama",
          "Please agree with our policy and terms":
              "Imaammataa fi haalawwan keenya irratti walii galaa",
          "Gender is a mandatory field": "Saala dirqama gutamuu qaba",
          "Something went wrong, please try again":
              "Wanti tokko dogoggora ta'e, maaloo irra deebi'ii yaalaa",
          "Account Created Successfuly": "Account Milkaa'inaan banamee",
          "This phone number is already registered":
              "Lakkoofsi bilbilaa kun duraan galmaa'ee jira",
          "Account creation failed please try again":
              "Uumamni herregaa hin milkoofne mee irra deebi'ii yaali",
          "Otp verified successfully": "Otp milkaa'inaan mirkanaa'e",
          "This field is required": "Dirree kun barbaachisaadha",
          "Please enter only letters": "Maaloo qubee qofa galchi",
          "Payment added Successfuly": "Kaffaltiin Milkaa'inaan darbeeraa",
          "payment process failed; please try again":
              "adeemsi kaffaltii hin milkoofne; maaloo irra deebi'ii yaali",
          "Do you want to Logout": "Ba'uu barbaaddaa",
          "Confirm Exit": "Ba'uu Mirkaneessi",
          "Confirm Deletion": "Haquu Mirkaneessi",
          "Are you sure you want to delete this user":
              "Fayyadamaa kana haquu akka barbaaddu mirkaneeffatteettaa,",
          "Account Deleted Successfuly": "Account Milkaa'inaan Haqame",
          "Account Updated Successfuly": "Account Milkaa'inaan Fooyyeffame",
          "Meeting created successfully": "Walgahiin milkaa'inaan uumamera",
          // "Amount repaid Successfuly": "Amount repaid Successfuly",
          "Loan repayment failed; please try again":
              "Kaffaltiin liqii hin milkoofne; maaloo irra deebi'ii yaalaa",
          "please select a member": "maaloo miseensa filadhu",
          "please enter a loan amount": "maaloo hanga liqii galchi",
          "The max amount of loan is": "Hanga liqii guddaan ",
          "Please enter a description": "Maaloo ibsa galchi",
          "please select a plan": "maaloo karoora filadhu",
          "Loan applied successfully": "Liqiin milkaa'inaan iyyatamera",
          "Password must be at least 6 characters long":
              "Jechi icciitii yoo xiqqaate arfii 6 dheerachuu qaba",
          "Password unmatched": "Jechi icciitii wal hin simne",
          "Phone number is required": "Lakkoofsi bilbilaa barbaachisa",
          "Enter a valid phone number": "Lakkoofsa bilbilaa sirrii galchi",
          "Member added successfully": "Miseensi milkaa'inaan dabalamera",
          "Meeting type is required": "Akkaataa walgahii barbaachisa",
          "Meeting inteval is required": "Walgahiin inteval barbaachisaadha",
          "Meeting activated successfully":
              "Walgahiin milkaa'inaan hojiirra oolera",
          "Meeting edited successfully": "Meeting edited successfully",
          "Meeting deleted successfully": "Walgahiin milkaa'inaan haqameera",
          "Are you sure, This process is irreversible":
              "Mirkanaa'aa jirtaa, Adeemsi kun kan hin deebinedha",
          "Attendance saved successfully": "Argamni milkaa'inaan guutamera",
          "Please fill attendace first": "Maaloo dursa attendace guutaa",
          // "No Penalties found": "No Penalties found",
          "Are you sure you want to add ..... Birr to ....":
              "Mirkaneeffattee ..... Birrii itti dabaluu barbaadduu ....",
          // "Meeting closed successfully": "Meeting closed successfully",
          "Please fill attendance before any payment":
              "Maaloo kaffaltii kamiyyuu dura attendance guutaa",
        },
      };
}
